### ISSUE TITLE
Move web3 / blockchain components to external package (aka: plugins)

### ISSUE THREAD

**Issue by gabitoesmiapodo** [BootNodeDev/dAppBooster#202] opened 2024-08-01 20:59 UTC
Similar to what we did with https://github.com/BootNodeDev/db-ui-toolkit

**Comment by gabitoesmiapodo** [comment] 2024-08-21 22:22
Are we going to keep working on this, or should we close the issue and remove the repo?

**Comment by fernandomg** [comment] 2024-08-22 11:17
> Are we going to keep working on this, or should we close the issue and delete the repo?

The idea was for me to continue working on this.

Not sure why we have now #242, I think that's a duplicate of this one.

**Comment by gabitoesmiapodo** [comment] 2024-09-05 15:17
This should be closed when https://github.com/BootNodeDev/dAppBoosterLandingPage/pull/8 is merged.

**Closed** 2024-09-10 08:35 UTC
